config/routes.rb
Rails.application.routes.draw do
  resources :portfolios
  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  resources :bloggs
  resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/blogg.rb
class Blogg < ApplicationRecord
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bloggs_controller.rb
class BloggsController < ApplicationController
  before_action :set_blogg, only: [:show, :edit, :update, :destroy]

  # GET /bloggs
  # GET /bloggs.json
  def index
    @bloggs = Blogg.all
  end

  # GET /bloggs/1
  # GET /bloggs/1.json
  def show
  end

  # GET /bloggs/new
  def new
    @blogg = Blogg.new
  end

  # GET /bloggs/1/edit
  def edit
  end

  # POST /bloggs
  # POST /bloggs.json
  def create
    @blogg = Blogg.new(blogg_params)

    respond_to do |format|
      if @blogg.save
        format.html { redirect_to @blogg, notice: 'Blogg was successfully created.' }
        format.json { render :show, status: :created, location: @blogg }
      else
        format.html { render :new }
        format.json { render json: @blogg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bloggs/1
  # PATCH/PUT /bloggs/1.json
  def update
    respond_to do |format|
      if @blogg.update(blogg_params)
        format.html { redirect_to @blogg, notice: 'Blogg was successfully updated.' }
        format.json { render :show, status: :ok, location: @blogg }
      else
        format.html { render :edit }
        format.json { render json: @blogg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bloggs/1
  # DELETE /bloggs/1.json
  def destroy
    @blogg.destroy
    respond_to do |format|
      format.html { redirect_to bloggs_url, notice: 'Blogg was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogg
      @blogg = Blogg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blogg_params
      params.require(:blogg).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  @Skills=Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def index
    @portfolio_items = Portfolio.all
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def create
    @portfolio_item = Portfolio.new(params.require(:portfolio).permit(:title, :subtitle, :body))

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Your portfolio item is now live.' }
      else
        format.html { render :new }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bloggs_helper.rb
module BloggsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/bloggs/_form.html.erb
<%= form_with(model: blogg, local: true) do |form| %>
  <% if blogg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blogg.errors.count, "error") %> prohibited this blogg from being saved:</h2>

      <ul>
      <% blogg.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blogg_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blogg_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bloggs/edit.html.erb
<h1>Editing Blogg</h1>

<%= render 'form', blogg: @blogg %>

<%= link_to 'Show', @blogg %> |
<%= link_to 'Back', bloggs_path %>

app/views/bloggs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bloggs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bloggs.each do |blogg| %>
      <tr>
        <td><%= blogg.title %></td>
        <td><%= blogg.body %></td>
        <td><%= link_to 'Show', blogg %></td>
        <td><%= link_to 'Edit', edit_blogg_path(blogg) %></td>
        <td><%= link_to 'Destroy', blogg, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blogg', new_blogg_path %>

app/views/bloggs/new.html.erb
<h1>New Blogg</h1>

<%= render 'form', blogg: @blogg %>

<%= link_to 'Back', bloggs_path %>

app/views/bloggs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blogg.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blogg.body %>
</p>

<%= link_to 'Edit', edit_blogg_path(@blogg) %> |
<%= link_to 'Back', bloggs_path %>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevcampPortfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>homePage</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<h1>Skills</h1>
<%= @skills.inspect %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>

<% @portfolio_items.each do |portfolio_item| %>
  <p><%= portfolio_item.title %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
<% end %>

app/views/portfolios/new.html.erb
<h1>Create a new Portfolio Item</h1>

<%= form_for(@portfolio_item) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>